import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { moneyForInput, parseMoneyInput, todayISO } from '../../../lib/finance'
import { ModalSurface } from '../../../components/ModalSurface'
import { ExpenseRecurrenceFields } from '../../expenses/components/ExpenseRecurrenceFields'
import type { IncomeDraft, IncomeOptions, IncomeRecord, IncomeStatus, RecurrenceFrequency } from '../types'
export function IncomeForm({ income, options, busy, error, onCancel, onSave }: { income: IncomeRecord|null; options: IncomeOptions; busy:boolean; error:string|null; onCancel:()=>void; onSave:(draft:IncomeDraft)=>Promise<void> }) {
  const editing=!!income, locked=!!income&&(income.status==='settled'||income.has_receipt_history)
  const [description,setDescription]=useState(income?.description??''), [categoryId,setCategoryId]=useState(income?.category_id??''), [amount,setAmount]=useState(income?moneyForInput(income.amount):''), [date,setDate]=useState(income?.transaction_date??todayISO()), [dueDate,setDueDate]=useState(income?.due_date??''), [notes,setNotes]=useState(income?.notes??''), [status,setStatus]=useState<IncomeStatus>(income?.status??'pending')
  const [accountId,setAccountId]=useState(''), [receivedAt,setReceivedAt]=useState(todayISO()), [recurring,setRecurring]=useState(false), [frequency,setFrequency]=useState<RecurrenceFrequency>('monthly'), [interval,setInterval]=useState('1'), [ending,setEnding]=useState<'none'|'date'|'count'>('none'), [endDate,setEndDate]=useState(''), [maxOccurrences,setMaxOccurrences]=useState(''), [recurrenceAccount,setRecurrenceAccount]=useState(''), [validation,setValidation]=useState<string|null>(null); const first=useRef<HTMLInputElement>(null)
  const categories=options.categories.filter((x)=>x.active||x.id===income?.category_id), accounts=options.accounts.filter((x)=>x.active||x.id===income?.account_id)
  useEffect(()=>{const old=document.activeElement as HTMLElement|null;first.current?.focus();return()=>old?.focus()},[])
  async function submit(e:FormEvent){e.preventDefault();if(busy)return;const value=parseMoneyInput(amount), n=Number(interval), max=Number(maxOccurrences)
    if(!description.trim()){setValidation('Informe a descrição da receita.');return} if(!categoryId){setValidation('Selecione uma categoria de receita.');return} if(value===null||value<=0){setValidation('Informe um valor maior que zero.');return} if(!date){setValidation('Informe a data da receita.');return} if(!editing&&status==='settled'&&(!accountId||!receivedAt)){setValidation('Informe a conta e a data do recebimento.');return} if(recurring&&(!Number.isInteger(n)||n<1)){setValidation('Informe um intervalo de recorrência válido.');return} if(recurring&&ending==='date'&&(!endDate||endDate<date)){setValidation('Informe uma data final válida.');return} if(recurring&&ending==='count'&&(!Number.isInteger(max)||max<1)){setValidation('Informe uma quantidade de ocorrências válida.');return}
    setValidation(null);await onSave({input:{description:description.trim(),category_id:categoryId,amount:value,transaction_date:date,due_date:dueDate||null,notes:notes.trim()||null},status,receipt:!editing&&status==='settled'?{account_id:accountId,received_at:receivedAt}:null,recurrence:recurring?{frequency,interval_count:n,end_date:ending==='date'?endDate:null,max_occurrences:ending==='count'?max:null,account_id:recurrenceAccount||null}:null})}
  return <ModalSurface titleId="income-form-title" className="account-modal expense-modal" busy={busy} onClose={onCancel}><h2 id="income-form-title">{editing?'Editar receita':'Nova receita'}</h2><p>Os campos marcados com * são obrigatórios.</p>{locked&&<p className="expense-lock-note">Há histórico financeiro. Apenas descrição e notas podem ser alteradas.</p>}<form onSubmit={submit} noValidate>
    <label htmlFor="income-description">Descrição *</label><input id="income-description" ref={first} value={description} onChange={(e)=>setDescription(e.target.value)} disabled={busy}/>
    <div className="expense-form-grid"><label htmlFor="income-category">Categoria *<select id="income-category" value={categoryId} onChange={(e)=>setCategoryId(e.target.value)} disabled={busy||locked}><option value="">Selecione</option>{categories.map((x)=><option key={x.id} value={x.id}>{x.name}{x.active?'':' (inativa)'}</option>)}</select></label><label htmlFor="income-amount">Valor (R$) *<input id="income-amount" value={amount} inputMode="decimal" onChange={(e)=>setAmount(e.target.value)} disabled={busy||locked}/></label><label htmlFor="income-date">Data da receita *<input id="income-date" type="date" value={date} onChange={(e)=>setDate(e.target.value)} disabled={busy||locked}/></label><label htmlFor="income-due">Data prevista de recebimento<input id="income-due" type="date" value={dueDate} onChange={(e)=>setDueDate(e.target.value)} disabled={busy||locked}/></label>{!editing&&<label htmlFor="income-status">Status inicial *<select id="income-status" value={status} onChange={(e)=>setStatus(e.target.value as IncomeStatus)} disabled={busy||recurring}><option value="pending">Pendente</option><option value="settled">Recebida</option></select></label>}</div>
    {!editing&&<><ExpenseRecurrenceFields noun="Receita" checked={recurring} frequency={frequency} interval={interval} ending={ending} endDate={endDate} maxOccurrences={maxOccurrences} disabled={busy||status==='settled'} onChecked={setRecurring} onFrequency={setFrequency} onInterval={setInterval} onEnding={setEnding} onEndDate={setEndDate} onMaxOccurrences={setMaxOccurrences}/>{recurring&&<label htmlFor="income-recurrence-account">Conta prevista<select id="income-recurrence-account" value={recurrenceAccount} onChange={(e)=>setRecurrenceAccount(e.target.value)} disabled={busy}><option value="">Não informada</option>{accounts.filter((x)=>x.active).map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}{status==='settled'&&<div className="expense-payment-fields"><div className="expense-form-grid"><label htmlFor="income-account">Conta de recebimento *<select id="income-account" value={accountId} onChange={(e)=>setAccountId(e.target.value)} disabled={busy}><option value="">Selecione</option>{accounts.filter((x)=>x.active).map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label htmlFor="income-received-at">Data do recebimento *<input id="income-received-at" type="date" value={receivedAt} onChange={(e)=>setReceivedAt(e.target.value)} disabled={busy}/></label></div></div>}</>}
    <label htmlFor="income-notes">Notas</label><textarea id="income-notes" value={notes} onChange={(e)=>setNotes(e.target.value)} rows={3} disabled={busy}/>{(validation||error)&&<p className="account-form-error" role="alert">{validation||error}</p>}<div className="account-form-actions"><button type="button" className="account-secondary-button" onClick={onCancel} disabled={busy}>Cancelar</button><button className="account-primary-button" disabled={busy}>{busy?'Salvando…':editing?'Salvar alterações':'Criar receita'}</button></div>
  </form></ModalSurface>
}
