import { getSupabaseClient } from '../../../lib/supabase'
import type { InvoiceDataset, InvoiceDetailsData, InvoiceRecord } from '../types'
export type InvoiceErrorKind='not_found'|'already_closed'|'already_paid'|'duplicate_payment'|'account'|'empty'|'blocked'|'permission'|'generic'
export class InvoiceServiceError extends Error{constructor(public readonly kind:InvoiceErrorKind){super(kind)}}
export function invoiceErrorKind(code?:string,message=''):InvoiceErrorKind{if(code==='42501'||code==='PGRST116')return'not_found';if(/empty invoice/i.test(message))return'empty';if(/already paid.*different|duplicate/i.test(message))return'duplicate_payment';if(/already paid/i.test(message))return'already_paid';if(/already closed/i.test(message))return'already_closed';if(/Active account|movement date|account.*invalid/i.test(message))return'account';if(code==='23514')return'blocked';if(code==='PGRST301')return'permission';return'generic'}
function check(error:{code?:string;message?:string}|null){if(error)throw new InvoiceServiceError(invoiceErrorKind(error.code,error.message))}
export async function listInvoices(userId:string):Promise<InvoiceDataset>{const c=getSupabaseClient();const[invoices,cards,accounts,totals,movements]=await Promise.all([c.from('credit_card_invoices').select('*').eq('user_id',userId).order('reference_month',{ascending:false}),c.from('credit_cards').select('*').eq('user_id',userId),c.from('accounts').select('*').eq('user_id',userId),c.from('invoice_totals').select('*').eq('user_id',userId),c.from('account_movements').select('id,origin_id').eq('user_id',userId).eq('origin_type','credit_card_payment')]);check(invoices.error);check(cards.error);check(accounts.error);check(totals.error);check(movements.error);const originals=movements.data??[],movementIds=originals.map(x=>x.id);const reversals=movementIds.length?await c.from('account_movements').select('reversal_of_movement_id').eq('user_id',userId).in('reversal_of_movement_id',movementIds):{data:[],error:null};check(reversals.error);const reversed=new Set((reversals.data??[]).map(x=>x.reversal_of_movement_id)),active=new Map(originals.filter(x=>!reversed.has(x.id)).map(x=>[x.origin_id,x.id])),history=new Set(originals.map(x=>x.origin_id)),cardMap=new Map((cards.data??[]).map(x=>[x.id,x])),accountMap=new Map((accounts.data??[]).map(x=>[x.id,x])),totalMap=new Map((totals.data??[]).map(x=>[x.invoice_id,x]));return{cards:cards.data??[],accounts:accounts.data??[],invoices:(invoices.data??[]).map(i=>{const card=cardMap.get(i.credit_card_id),total=totalMap.get(i.id);return{...i,card_name:card?.name??'Cartão indisponível',card_active:card?.active??false,payment_account_name:i.payment_account_id?accountMap.get(i.payment_account_id)?.name??'Conta indisponível':null,total_amount:total?.total_amount??0,transaction_count:total?.transaction_count??0,payment_movement_id:active.get(i.id)??null,has_payment_history:history.has(i.id)} as InvoiceRecord})}}
export async function getInvoiceDetails(userId:string,invoice:InvoiceRecord):Promise<InvoiceDetailsData>{const c=getSupabaseClient();const{data,error}=await c.from('transactions').select('*').eq('user_id',userId).eq('credit_card_invoice_id',invoice.id).order('transaction_date',{ascending:true});check(error);const categoryIds=[...new Set((data??[]).map(x=>x.category_id))];const categories=categoryIds.length?await c.from('categories').select('id,name').eq('user_id',userId).in('id',categoryIds):{data:[],error:null};check(categories.error);const names=new Map((categories.data??[]).map(x=>[x.id,x.name]));return{invoice,items:(data??[]).map(x=>({...x,category_name:names.get(x.category_id)??'Categoria indisponível'}))}}
export async function closeInvoice(id:string){const{error}=await getSupabaseClient().rpc('close_invoice',{p_invoice_id:id});check(error)}
export async function payInvoice(id:string,accountId:string,paidAt:string){const{error}=await getSupabaseClient().rpc('pay_invoice',{p_invoice_id:id,p_account_id:accountId,p_paid_at:paidAt});check(error)}
export async function reverseInvoicePayment(movementId:string,reversedAt:string){const{error}=await getSupabaseClient().rpc('reverse_movement',{p_movement_id:movementId,p_reversed_at:reversedAt});check(error)}
