import type { ReactNode } from 'react'
import { formatBRDate, formatBRL } from '../../../lib/finance'
import type { AccountBalanceItem, CardSummary, UpcomingInvoice, UpcomingTransaction } from '../types'
import { PrivateAmount } from '../../privacy/PrivateAmount'
function Panel({title,children}:{title:string;children:ReactNode}){const id=title.replaceAll(' ','-').toLowerCase();return <section className="dashboard-panel dashboard-list-panel" aria-labelledby={id}><div className="dashboard-panel-heading"><h2 id={id}>{title}</h2></div>{children}</section>}
export function AccountBalancesList({items}:{items:AccountBalanceItem[]}){return <Panel title="Saldo por conta">{!items.length?<p className="dashboard-panel-empty">Nenhuma conta ativa.</p>:<div className="dashboard-simple-list">{items.map((item)=><div key={item.id}><span>{item.name}</span><strong><PrivateAmount value={item.balance}/></strong></div>)}</div>}</Panel>}
export function UpcomingTransactions({title,items,dateLabel}:{title:string;items:UpcomingTransaction[];dateLabel:string}){return <Panel title={title}>{!items.length?<p className="dashboard-panel-empty">Nenhum item previsto no período.</p>:<div className="dashboard-detailed-list">{items.map((item)=><article key={item.id}><div><strong>{item.description}</strong><span>{item.categoryName} · {dateLabel} {formatBRDate(item.dueDate)}</span></div><b>{formatBRL(item.amount)}</b></article>)}</div>}</Panel>}
export function UpcomingInvoices({items}:{items:UpcomingInvoice[]}){return <Panel title="Faturas próximas">{!items.length?<p className="dashboard-panel-empty">Nenhuma fatura pendente no período.</p>:<div className="dashboard-detailed-list">{items.map((item)=><article key={item.id}><div><strong>{item.cardName}</strong><span>{item.status==='open'?'Aberta':'Fechada'} · vence em {formatBRDate(item.dueDate)}</span></div><b><PrivateAmount value={item.amount}/></b></article>)}</div>}</Panel>}
export function CardsSummary({items}:{items:CardSummary[]}){return <Panel title="Cartões">{!items.length?<p className="dashboard-panel-empty">Nenhum cartão ativo.</p>:<div className="dashboard-detailed-list">{items.map((item)=><article key={item.id}><div><strong>{item.name}</strong><span>Limite cadastrado: <PrivateAmount value={item.limit}/></span></div><b>{item.invoice?<PrivateAmount value={item.invoice.amount}/>:'Sem fatura'}</b></article>)}</div>}</Panel>}
