import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import type { User } from '@supabase/supabase-js'
import { AuthContext } from '../features/auth/auth-context'
import type { AuthState } from '../features/auth/auth-context'
import type { IncomeDataset, IncomeRecord, RecurrenceFrequency } from '../features/incomes/types'
import { IncomeServiceError, createIncome, createReceivedIncome, createRecurringIncome, deleteIncome, generateIncomeOccurrences, listIncomes, reverseIncomeReceipt, settleIncome, updateIncome } from '../features/incomes/services/incomes'
import { IncomesPage } from './IncomesPage'
vi.mock('../features/incomes/services/incomes',async(importOriginal)=>{const original=await importOriginal<typeof import('../features/incomes/services/incomes')>();return{...original,listIncomes:vi.fn(),createIncome:vi.fn(),createReceivedIncome:vi.fn(),createRecurringIncome:vi.fn(),deleteIncome:vi.fn(),generateIncomeOccurrences:vi.fn(),reverseIncomeReceipt:vi.fn(),settleIncome:vi.fn(),updateIncome:vi.fn()}})
const user={id:'user-income'} as User, auth:AuthState={user,session:null,profile:null,loading:false,error:null}
const category={id:'cat-income',user_id:user.id,name:'Salário',type:'income',active:true,created_at:'2026-01-01',updated_at:'2026-01-01'} as const
const account={id:'acc-1',user_id:user.id,name:'Conta principal',type:'checking',initial_balance:0,initial_balance_date:'2020-01-01',active:true,created_at:'2026-01-01',updated_at:'2026-01-01'} as const
const base={id:'income-1',user_id:user.id,type:'income',description:'Salário',category_id:category.id,amount:5000,transaction_date:'2026-09-30',due_date:'2026-10-05',status:'pending',planned_payment_method:'bank_transfer',actual_payment_method:null,account_id:null,credit_card_id:null,credit_card_invoice_id:null,installment_group_id:null,installment_number:null,installment_total:null,recurrence_rule_id:null,settled_at:null,notes:null,created_at:'2026-09-01',updated_at:'2026-09-01',category_name:'Salário',account_name:null,receipt_movement_id:null,has_receipt_history:false,recurrence_frequency:null,recurrence_interval_count:null} as IncomeRecord
const dataset=(incomes:IncomeRecord[]=[]):IncomeDataset=>({incomes,options:{categories:[category],accounts:[account]}})
function mount(){return render(<AuthContext.Provider value={auth}><IncomesPage/></AuthContext.Provider>)}
async function loaded(){await waitFor(()=>expect(screen.queryByText('Carregando receitas…')).toBeNull())}
function open(){fireEvent.click(screen.getAllByRole('button',{name:'Nova receita'})[0]!)}
function fill(){fireEvent.change(screen.getByLabelText('Descrição *'),{target:{value:'  Projeto  '}});fireEvent.change(screen.getByLabelText('Categoria *'),{target:{value:category.id}});fireEvent.change(screen.getByLabelText('Valor (R$) *'),{target:{value:'1.500,25'}});fireEvent.change(screen.getByLabelText('Data da receita *'),{target:{value:'2026-09-15'}})}
function submit(){fireEvent.click(screen.getByRole('button',{name:'Criar receita'}))}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(listIncomes).mockResolvedValue(dataset());for(const fn of[createIncome,createReceivedIncome,createRecurringIncome,deleteIncome,reverseIncomeReceipt,settleIncome,updateIncome])vi.mocked(fn).mockResolvedValue();vi.mocked(generateIncomeOccurrences).mockResolvedValue(0)})
afterEach(()=>{cleanup();vi.restoreAllMocks()})
test('1: renderização',async()=>{mount();await loaded();expect(screen.getByRole('heading',{name:'Receitas',level:1})).toBeTruthy();expect(listIncomes).toHaveBeenCalledWith(user.id,expect.any(String),expect.any(String))})
test('2: estado vazio',async()=>{mount();await loaded();expect(screen.getByText('Nenhuma receita encontrada.')).toBeTruthy();open();expect(screen.getByRole('dialog')).toBeTruthy()})
test('3: listagem',async()=>{vi.mocked(listIncomes).mockResolvedValue(dataset([base]));mount();await loaded();expect(screen.getByRole('heading',{name:'Salário',level:2})).toBeTruthy();expect(screen.getAllByText(/R\$\s*5\.000,00/).length).toBeGreaterThan(0)})
test('4: filtro por período',async()=>{mount();await loaded();fireEvent.change(screen.getByLabelText('Data inicial'),{target:{value:'2026-08-01'}});await waitFor(()=>expect(listIncomes).toHaveBeenLastCalledWith(user.id,'2026-08-01',expect.any(String)))})
test('5: filtro por status',async()=>{const received={...base,id:'r',description:'Recebida',status:'settled' as const};vi.mocked(listIncomes).mockResolvedValue(dataset([base,received]));mount();await loaded();fireEvent.change(screen.getByLabelText('Status'),{target:{value:'settled'}});expect(screen.getByRole('heading',{name:'Recebida',level:2})).toBeTruthy();expect(screen.queryByText('Pendente')).toBeNull()})
test('6: filtro por categoria',async()=>{const other={...base,id:'o',category_id:'other',category_name:'Outra'};vi.mocked(listIncomes).mockResolvedValue(dataset([base,other]));mount();await loaded();fireEvent.change(screen.getByLabelText('Categoria'),{target:{value:category.id}});expect(screen.queryByText('Outra')).toBeNull()})
test('7: criação pendente',async()=>{mount();await loaded();open();fill();submit();await waitFor(()=>expect(createIncome).toHaveBeenCalledWith(user.id,expect.objectContaining({description:'Projeto',amount:1500.25})))})
test('8: criação já recebida',async()=>{mount();await loaded();open();fill();fireEvent.change(screen.getByLabelText('Status inicial *'),{target:{value:'settled'}});fireEvent.change(screen.getByLabelText('Conta de recebimento *'),{target:{value:account.id}});submit();await waitFor(()=>expect(createReceivedIncome).toHaveBeenCalledWith(expect.any(Object),account.id,expect.any(String)))})
test('9: conta obrigatória ao receber',async()=>{mount();await loaded();open();fill();fireEvent.change(screen.getByLabelText('Status inicial *'),{target:{value:'settled'}});submit();expect(screen.getByRole('alert').textContent).toContain('conta');expect(createReceivedIncome).not.toHaveBeenCalled()})
test('10: marcar como recebida',async()=>{vi.mocked(listIncomes).mockResolvedValue(dataset([base]));mount();await loaded();fireEvent.click(screen.getByRole('button',{name:'Marcar como recebida'}));fireEvent.change(screen.getByLabelText('Conta *'),{target:{value:account.id}});fireEvent.click(screen.getByRole('button',{name:'Confirmar recebimento'}));await waitFor(()=>expect(settleIncome).toHaveBeenCalledWith(base.id,account.id,expect.any(String)))})
test('11: estornar recebimento',async()=>{vi.spyOn(window,'confirm').mockReturnValue(true);const item={...base,status:'settled' as const,receipt_movement_id:'mov-1',has_receipt_history:true};vi.mocked(listIncomes).mockResolvedValue(dataset([item]));mount();await loaded();fireEvent.click(screen.getByRole('button',{name:'Desfazer recebimento'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar estorno'}));await waitFor(()=>expect(reverseIncomeReceipt).toHaveBeenCalledWith('mov-1',expect.any(String)))})
test('12: edição pendente',async()=>{vi.mocked(listIncomes).mockResolvedValue(dataset([base]));mount();await loaded();fireEvent.click(screen.getByRole('button',{name:'Editar'}));fireEvent.change(screen.getByLabelText('Descrição *'),{target:{value:'Salário editado'}});fireEvent.click(screen.getByRole('button',{name:'Salvar alterações'}));await waitFor(()=>expect(updateIncome).toHaveBeenCalledWith(base.id,expect.objectContaining({description:'Salário editado'})))})
test('13: bloqueio financeiro após recebimento',async()=>{const item={...base,status:'settled' as const,has_receipt_history:true};vi.mocked(listIncomes).mockResolvedValue(dataset([item]));mount();await loaded();fireEvent.click(screen.getByRole('button',{name:'Editar'}));expect((screen.getByLabelText('Valor (R$) *') as HTMLInputElement).disabled).toBe(true);expect(screen.getByText(/Apenas descrição e notas/)).toBeTruthy()})
test('14: exclusão pendente',async()=>{vi.spyOn(window,'confirm').mockReturnValue(true);vi.mocked(listIncomes).mockResolvedValue(dataset([base]));mount();await loaded();fireEvent.click(screen.getByRole('button',{name:'Excluir'}));await waitFor(()=>expect(deleteIncome).toHaveBeenCalledWith(user.id,base.id))})
test('15: bloqueio de exclusão com histórico',async()=>{vi.spyOn(window,'confirm').mockReturnValue(true);vi.mocked(deleteIncome).mockRejectedValue(new IncomeServiceError('history'));vi.mocked(listIncomes).mockResolvedValue(dataset([base]));mount();await loaded();fireEvent.click(screen.getByRole('button',{name:'Excluir'}));await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('Desfaça o recebimento'))})
for(const [n,frequency] of [[16,'daily'],[17,'weekly'],[18,'monthly'],[19,'yearly']] as [number,RecurrenceFrequency][])test(`${n}: recorrência ${frequency}`,async()=>{mount();await loaded();open();fill();fireEvent.click(screen.getByLabelText('Receita recorrente'));fireEvent.change(screen.getByLabelText('Periodicidade *'),{target:{value:frequency}});submit();await waitFor(()=>expect(createRecurringIncome).toHaveBeenCalledWith(expect.any(Object),expect.objectContaining({frequency}),expect.any(String)))})
test('20: erro de API amigável',async()=>{vi.mocked(createIncome).mockRejectedValue(new Error('raw postgres'));mount();await loaded();open();fill();submit();await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('Não foi possível concluir'));expect(screen.queryByText('raw postgres')).toBeNull()})
test('21: previne submit duplo',async()=>{vi.mocked(createIncome).mockReturnValue(new Promise(()=>undefined));mount();await loaded();open();fill();const button=screen.getByRole('button',{name:'Criar receita'});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(screen.getByRole('button',{name:'Salvando…'}).hasAttribute('disabled')).toBe(true));expect(createIncome).toHaveBeenCalledTimes(1)})
