import { useState } from 'react'
import { ArrowUpRight, Plus, RefreshCw } from 'lucide-react'
import { useAuth } from '../hooks/useAuth'
import { IncomeCard } from '../features/incomes/components/IncomeCard'
import { IncomeFilters } from '../features/incomes/components/IncomeFilters'
import { IncomeForm } from '../features/incomes/components/IncomeForm'
import { IncomeReceiptDialog } from '../features/incomes/components/IncomeReceiptDialog'
import { useIncomes } from '../features/incomes/hooks/useIncomes'
import { IncomeServiceError } from '../features/incomes/services/incomes'
import type { IncomeDraft, IncomeRecord } from '../features/incomes/types'
import { formatBRL } from '../lib/finance'
function friendly(error:unknown){if(error instanceof IncomeServiceError){return({permission:'Você não tem permissão para realizar esta operação.',category:'A categoria selecionada não é uma categoria de receita ativa.',account:'A conta selecionada não é válida para este recebimento.',already_received:'Esta receita já foi recebida.',already_reversed:'Este recebimento já foi desfeito.',history:'Desfaça o recebimento antes de alterar ou excluir esta receita.',validation:'Confira os dados da receita e tente novamente.',generic:'Não foi possível concluir a operação. Tente novamente.'})[error.kind]}return'Não foi possível concluir a operação. Tente novamente.'}
export function IncomesPage(){const{user}=useAuth(),data=useIncomes(user?.id??null);const[editing,setEditing]=useState<IncomeRecord|null|undefined>(undefined),[receipt,setReceipt]=useState<{income:IncomeRecord;mode:'receive'|'reverse'}|null>(null),[formError,setFormError]=useState<string|null>(null),[message,setMessage]=useState<{text:string;error:boolean}|null>(null);const total=data.allIncomes.reduce((s,x)=>s+x.amount,0),pending=data.allIncomes.filter((x)=>x.status==='pending').reduce((s,x)=>s+x.amount,0)
  async function save(draft:IncomeDraft){const result=editing?await data.update(editing.id,draft.input):await data.create(draft);if(!result.ok){setFormError(friendly(result.error));return}setEditing(undefined);setMessage({text:editing?'Receita atualizada com sucesso.':'Receita criada com sucesso.',error:false})}
  async function remove(item:IncomeRecord){if(!window.confirm(`Excluir a receita “${item.description}”?`))return;const r=await data.remove(item.id);setMessage(r.ok?{text:'Receita excluída com sucesso.',error:false}:{text:friendly(r.error),error:true})}
  async function confirmReceipt(accountId:string,date:string){if(!receipt)return;const r=receipt.mode==='receive'?await data.receive(receipt.income.id,accountId,date):receipt.income.receipt_movement_id?await data.reverse(receipt.income.receipt_movement_id,date):{ok:false as const,error:new Error()};if(!r.ok){setFormError(friendly(r.error));return}setReceipt(null);setFormError(null);setMessage({text:receipt.mode==='receive'?'Receita recebida com sucesso.':'Recebimento desfeito com sucesso.',error:false})}
  async function generate(){const r=await data.generate();setMessage(r.ok?{text:r.value?`${r.value} ocorrência(s) recorrente(s) gerada(s).`:'As recorrências já estão atualizadas.',error:false}:{text:friendly(r.error),error:true})}
  return <section className="incomes-page"><div className="page-heading"><div><p className="eyebrow">RECEBIMENTOS</p><h1>Receitas</h1><p>Acompanhe seus recebimentos.</p></div><div className="expense-heading-actions"><button className="account-secondary-button" onClick={generate} disabled={data.busy}><RefreshCw size={17}/> Atualizar recorrências</button><button className="account-primary-button" onClick={()=>{setEditing(null);setFormError(null)}} disabled={data.busy}><Plus size={18}/> Nova receita</button></div></div>
    {message&&<p className={message.error?'account-notice account-notice-error':'account-notice'} role={message.error?'alert':'status'}>{message.text}</p>}<IncomeFilters {...data.filters} categories={data.options.categories} onStartDate={data.setStartDate} onEndDate={data.setEndDate} onStatus={data.setStatus} onCategory={data.setCategoryId}/>{data.invalidPeriod&&<p className="account-notice account-notice-error" role="alert">A data inicial deve ser anterior ou igual à data final.</p>}
    <div className="expense-summary" aria-label="Totais do período"><div><span>Total</span><strong>{formatBRL(total)}</strong></div><div><span>Pendentes</span><strong>{formatBRL(pending)}</strong></div><div><span>Recebidas</span><strong>{formatBRL(total-pending)}</strong></div></div>
    {data.loading&&<div className="account-state" role="status"><div className="loading-spinner"/> Carregando receitas…</div>}{!data.loading&&data.error&&<div className="account-state" role="alert"><p>Não foi possível carregar suas receitas.</p><button className="account-secondary-button" onClick={data.refresh}>Tentar novamente</button></div>}{!data.loading&&!data.error&&!data.invalidPeriod&&!data.incomes.length&&<div className="account-state"><span className="placeholder-icon"><ArrowUpRight size={27}/></span><h2>Nenhuma receita encontrada.</h2><button className="account-primary-button" onClick={()=>setEditing(null)}>Nova receita</button></div>}{!data.loading&&!data.error&&data.incomes.length>0&&<div className="account-grid">{data.incomes.map((item)=><IncomeCard key={item.id} income={item} busy={data.busy} onEdit={()=>{setEditing(item);setFormError(null)}} onReceive={()=>{setReceipt({income:item,mode:'receive'});setFormError(null)}} onReverse={()=>{if(window.confirm('Deseja desfazer este recebimento?')){setReceipt({income:item,mode:'reverse'});setFormError(null)}}} onDelete={()=>remove(item)}/>)}</div>}
    {editing!==undefined&&<IncomeForm income={editing} options={data.options} busy={data.busy} error={formError} onCancel={()=>setEditing(undefined)} onSave={save}/>} {receipt&&<IncomeReceiptDialog mode={receipt.mode} accounts={data.options.accounts} busy={data.busy} error={formError} onCancel={()=>setReceipt(null)} onConfirm={confirmReceipt}/>}</section>}
